server:
  port: 8080

JWT:
  SECRET: ${JWT_SECRET}

spring:
  application:
    name: backend

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3306/jipangi_db?useSSL=false&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true  # ??? SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL? ?? ?? ???
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50  # ? ?? ??? ??? ?
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


# Swagger 3.0 ??
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true


# ?? ??? (?? ???)
#  servlet:
#    multipart:
#      max-file-size: 10MB  # ?? ??? ?? ??
#      max-request-size: 10MB  # ??? ?? ?? ??
#    web:
#      resources:
#        static-locations: classpath:/static/  # ?? ??? ??
#
#  file:
#    upload-dir: uploads  # ?? ??? ????

# ???? ??
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,metrics,health  # ??? ??????
#  endpoint:
#    prometheus:
#      enabled: true  # Prometheus ????? ???
