server:
  port: 8080

JWT:
  SECRET: ${JWT_SECRET}

card:
  py:
    data:
      path: ${CRAWLER_JSON:./crawler/card_data.json}
    file:
      path: ${CRAWLER_PY:./crawler/card_crawler.py}

spring:
  application:
    name: backend

  config:
    import: classpath:application-API-KEY.properties


  # 도커용
  #  data:
  #    redis:
  #      host: redis
  #      port: 6379
  #      password:

  # 로컬용
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password:

  # 도커용
  #  datasource:
  #    url: jdbc:mariadb://localhost:3306/jipangi_db?useSSL=false&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  #    username: ${DATABASE_USERNAME:user}
  #    password: ${DATABASE_PASSWORD:1234}
  #    driver-class-name: org.mariadb.jdbc.Driver

  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/doubly_db?useSSL=false&allwowPublicKeyRetrieval=true&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true  # ??? SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL? ?? ?? ???
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50  # ? ?? ??? ??? ?
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


# Swagger 3.0 ??
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true

br:
  api:
    url: http://${BR_HOST:localhost}:8084

pos:
  api:
    url: http://${POS_HOST:localhost}:8083

bank:
  api:
    url: http://${BANK_HOST:localhost}:8081


